### ISSUE TITLE
How do I disable build option when I deploy the war file 

### ISSUE THREAD

**Issue by nanduahmed** [Deanly/just-start-server-vscode-extension#2]
I have installed this extension. When I hit run, it starts building. How do I disable build option when I deploy the war file

**Comment by Deanly** [comment]
It can not yet. I know its necessity. I will update some time soon.
this extension was created to help markup developers who have not running the server.

**Comment by Deanly** [comment]
I have made the distribution for you. 
https://github.com/Deanly/just-start-server-vscode-extension/releases/tag/0.2.0
